spring:
  main:
    banner-mode: off
xplan:
  authentication:
    login-path: /resourceful/session/user
    username: ${XPLAN_USERNAME}
    password: ${XPLAN_PASSWORD}
    api-key-name: X-Xplan-App-Id
    api-key-value: ${XPLAN_APP_ID}
logging:
  level:
    root: error
